"""
Random tables - adopted from _Knave_.

"""

# Character generation tables

chargen_tables = {
    "physique": [
        "athletic",
        "brawny",
        "corpulent",
        "delicate",
        "gaunt",
        "hulking",
        "lanky",
        "ripped",
        "rugged",
        "scrawny",
        "short",
        "sinewy",
        "slender",
        "flabby",
        "statuesque",
        "stout",
        "tiny",
        "towering",
        "willowy",
        "wiry",
    ],
    "face": [
        "bloated",
        "blunt",
        "bony",
        "chiseled",
        "delicate",
        "elongated",
        "patrician",
        "pinched",
        "hawkish",
        "broken",
        "impish",
        "narrow",
        "ratlike",
        "round",
        "sunken",
        "sharp",
        "soft",
        "square",
        "wide",
        "wolfish",
    ],
    "skin": [
        "battle scar",
        "birthmark",
        "burn scar",
        "dark",
        "makeup",
        "oily",
        "pale",
        "perfect",
        "pierced",
        "pockmarked",
        "reeking",
        "tattooed",
        "rosy",
        "rough",
        "sallow",
        "sunburned",
        "tanned",
        "war paint",
        "weathered",
        "whip scar",
    ],
    "hair": [
        "bald",
        "braided",
        "bristly",
        "cropped",
        "curly",
        "disheveled",
        "dreadlocks",
        "filthy",
        "frizzy",
        "greased",
        "limp",
        "long",
        "luxurious",
        "mohawk",
        "oily",
        "ponytail",
        "silky",
        "topknot",
        "wavy",
        "wispy",
    ],
}
